// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AsideBase: typeof import('./components/AsideBase.vue')['default']
    AsideTools: typeof import('./components/AsideTools.vue')['default']
    ContentWrapper: typeof import('./components/ContentWrapper.vue')['default']
    FjProfileData: typeof import('./components/FjProfileData.vue')['default']
    ProfileCard: typeof import('./components/ProfileCard.vue')['default']
    ProfileData: typeof import('./components/ProfileData.vue')['default']
    ProfileDataElement: typeof import('./components/ProfileDataElement.vue')['default']
    ProfileSkills: typeof import('./components/ProfileSkills.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
  }
}

export { }
